
    ersion: '3.1'

    services:
      tb:
        depends_on:
          - jrtb-db
        build:
          context: .
        environment:
          - tb.env
          BOT_NAME: ${BOT_NAME}
          BOT_TOKEN: ${BOT_TOKEN}
          BOT_DB_USERNAME: ${BOT_DB_USERNAME}
          BOT_DB_PASSWORD: ${BOT_DB_PASSWORD}
        restart: always
      jrtb-db:
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_USER: ${BOT_DB_USERNAME}
          MYSQL_PASSWORD: ${BOT_DB_PASSWORD}
          MYSQL_DATABASE: jrtb_db
          MYSQL_ROOT_PASSWORD: userroot
        ports:
          - 3306:3306
        expose:
          - 3306