services:
  tb-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: telegram_bot_database
      # So you don't have to use root, but you can if you like
      MYSQL_USER: bestuser
      # You can use whatever password you like
      MYSQL_PASSWORD: bestuser
      # Password for root access
      MYSQL_ROOT_PASSWORD: userroot
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3307:3306
    expose:
      # Opens port 3306 on the container
      - 3307